In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [29]:
lr = LogisticRegression()

lr.fit(X_train, Y_train)
lr.score(X_test, Y_test)

d:\Work\On\ml\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9388888888888889

In [30]:
svm = SVC()
svm.fit(X_train, Y_train)
svm.score(X_test, Y_test)

0.9907407407407407

In [31]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, Y_train)
rf.score(X_test, Y_test)

0.9685185185185186

In [32]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [33]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [3 4 5 6 7 8] TEST: [0 1 2]
TRAIN: [0 1 2 6 7 8] TEST: [3 4 5]
TRAIN: [0 1 2 3 4 5] TEST: [6 7 8]


In [34]:
def get_score(model, X_tain, X_test, Y_train, Y_test):
    model.fit(X_train, Y_train)
    return model.score(X_test, Y_test)

In [35]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [36]:
scores_l = []
scores_s = []
scores_r = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, Y_train, Y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    
    scores_l.append(get_score(LogisticRegression(), X_train, X_test, Y_train, Y_test))
    scores_s.append(get_score(SVC(), X_train, X_test, Y_train, Y_test))
    scores_r.append(get_score(RandomForestClassifier(), X_train, X_test, Y_train, Y_test))

d:\Work\On\ml\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Work\On\ml\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the

In [37]:
scores_l, scores_s, scores_r

([0.9232053422370617, 0.9415692821368948, 0.9148580968280468],
 [0.9666110183639399, 0.9816360601001669, 0.9549248747913188],
 [0.9499165275459098, 0.9515859766277128, 0.9198664440734557])

In [38]:
# for do above task we can use cross_val_score
from sklearn.model_selection import cross_val_score

cross_val_score(LogisticRegression(), digits.data, digits.target)

d:\Work\On\ml\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Work\On\ml\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [39]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [40]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.93333333, 0.91111111, 0.94150418, 0.95821727, 0.94150418])

In [41]:
cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target)

array([0.83611111, 0.8       , 0.88579387, 0.90529248, 0.85236769])

In [42]:
cross_val_score(RandomForestClassifier(n_estimators=10), digits.data, digits.target)

array([0.89166667, 0.85      , 0.91643454, 0.94986072, 0.91086351])

In [43]:
def get_average(arr):
    return np.mean(arr)

In [44]:
av_l = get_average(scores_l)
av_s = get_average(scores_s)
av_r = get_average(scores_r)

av_l, av_s, av_r

(np.float64(0.9265442404006677),
 np.float64(0.9677239844184752),
 np.float64(0.9404563160823595))